# Generated by Django 4.1.4 on 2023-01-15 08:32

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plantation',
            fields=[
                ('Plantation_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Plantation_name', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=50)),
                ('State', models.CharField(max_length=50)),
                ('Postcode', models.CharField(max_length=50)),
                ('Gps', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
                ('Total_Area', models.FloatField(default=0.0, null=True)),
                ('Plantation_desc', models.TextField(blank=True, null=True)),
                ('Listed_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Plantation_GIS',
            fields=[
                ('Plantation_GIS_id', models.AutoField(primary_key=True, serialize=False)),
                ('Raster', models.ImageField(null=True, upload_to='Raster/%Y_%m_%d/')),
                ('DSM', models.ImageField(null=True, upload_to='DSM/%Y_%m_%d/')),
                ('DTM', models.ImageField(null=True, upload_to='DTM/%Y_%m_%d/')),
                ('Flow', models.ImageField(null=True, upload_to='Flow/%Y_%m_%d/')),
                ('Vari', models.ImageField(null=True, upload_to='Vari/%Y_%m_%d/')),
                ('IMG_bound_1', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
                ('IMG_bound_2', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
                ('Upload_Date', models.DateField(auto_now_add=True)),
                ('Plantation_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Estate.plantation')),
            ],
        ),
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('Plot_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Plot_name', models.CharField(max_length=100, null=True)),
                ('Planted_area', models.FloatField(default=0.0, null=True)),
                ('Area_size', models.FloatField(default=0.0, null=True)),
                ('Gps', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
                ('Boudary', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('Listed_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Plot_desc', models.TextField(blank=True, null=True)),
                ('Plantation_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Estate.plantation')),
            ],
        ),
        migrations.CreateModel(
            name='Trees_Health_Info',
            fields=[
                ('Tree_Health_id', models.AutoField(primary_key=True, serialize=False)),
                ('Timestamp', models.DateField(auto_now_add=True)),
                ('Pixel_X', models.FloatField(default=0.0, null=True)),
                ('Pixel_Y', models.FloatField(default=0.0, null=True)),
                ('Coordinate_X', models.FloatField(default=0.0, null=True)),
                ('Coordinate_Y', models.FloatField(default=0.0, null=True)),
                ('Gps', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
                ('Mean_vari', models.FloatField(default=0.0, null=True)),
                ('Health_class', models.CharField(max_length=100)),
                ('Plantation_GIS_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Estate.plantation_gis')),
                ('Plot_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Estate.plot')),
            ],
        ),
        migrations.CreateModel(
            name='Trees',
            fields=[
                ('Tree_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Listed_date', models.DateTimeField(auto_now_add=True)),
                ('Gps', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
                ('Plot_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Estate.plot')),
            ],
        ),
    ]
