# Generated by Django 4.1.4 on 2023-01-06 10:40

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plantation',
            fields=[
                ('Plantation_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Plantation_name', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=50)),
                ('State', models.CharField(max_length=50)),
                ('Postcode', models.CharField(max_length=50)),
                ('Gps', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
                ('Total_Area', models.FloatField(default=0.0, null=True)),
                ('Plantation_desc', models.TextField(blank=True, null=True)),
                ('Listed_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('Plot_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Plot_name', models.CharField(max_length=100)),
                ('Planted_area', models.FloatField(default=0.0, null=True)),
                ('Area_size', models.FloatField(default=0.0, null=True)),
                ('Gps', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
                ('Boudary', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('Listed_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Plot_desc', models.TextField(blank=True, null=True)),
                ('Plantation_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='location.plantation')),
            ],
        ),
    ]
