# Generated by Django 4.1.4 on 2023-01-09 03:40

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_plantation_plot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tree_Tag',
            fields=[
                ('Tree_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Gps', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
                ('Listed_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Plot_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='location.plot')),
            ],
        ),
        migrations.AddConstraint(
            model_name='tree_tag',
            constraint=models.UniqueConstraint(fields=('Tree_id', 'Listed_date'), name='unique_Tree_Date_Combination'),
        ),
    ]
