# Generated by Django 4.1.4 on 2023-01-09 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_tree_tag_tree_tag_unique_tree_date_combination'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tree_tag',
            name='unique_Tree_Date_Combination',
        ),
        migrations.AlterField(
            model_name='tree_tag',
            name='Tree_id',
            field=models.AutoField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
