# Generated by Django 4.1.4 on 2023-01-09 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0005_alter_tree_tag_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyTable',
            fields=[
                ('key1', models.IntegerField(primary_key=True, serialize=False)),
                ('key2', models.IntegerField()),
            ],
            options={
                'unique_together': {('key1', 'key2')},
            },
        ),
    ]
