# Generated by Django 4.1.4 on 2023-01-09 04:59

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0006_mytable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tree_tag',
            name='Tree_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Trees',
            fields=[
                ('Tree_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Listed_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Gps', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
                ('Plot_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='location.plot')),
            ],
        ),
    ]
