# Generated by Django 4.1.4 on 2023-01-09 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0007_alter_tree_tag_tree_id_trees'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyTable',
        ),
        migrations.DeleteModel(
            name='Tree_Tag',
        ),
    ]
