# Generated by Django 4.1.4 on 2023-01-09 05:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0008_delete_mytable_delete_tree_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trees_Health',
            fields=[
                ('Timestamp', models.DateTimeField(default=django.utils.timezone.now, primary_key=True, serialize=False)),
                ('Mean_vari', models.FloatField(default=0.0, null=True)),
                ('Health_class', models.CharField(max_length=100)),
                ('Tree_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='location.trees')),
            ],
        ),
    ]
