# Generated by Django 4.1.4 on 2023-01-09 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0009_trees_health'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trees_health',
            name='Timestamp',
            field=models.DateTimeField(primary_key=True, serialize=False),
        ),
    ]
