# Generated by Django 4.1.4 on 2023-01-09 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0012_alter_trees_health_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trees_health',
            name='Timestamp',
            field=models.DateTimeField(auto_now_add=True, primary_key=True, serialize=False),
        ),
    ]
