# Generated by Django 4.1.4 on 2023-01-09 13:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0013_alter_trees_health_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trees_health',
            name='Timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, primary_key=True, serialize=False),
        ),
    ]
