# Generated by Django 4.1.4 on 2023-01-14 05:21

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0014_alter_trees_health_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trees',
            name='Listed_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='Plantation_GIS',
            fields=[
                ('Plantation_GIS_id', models.AutoField(primary_key=True, serialize=False)),
                ('Raster', models.ImageField(upload_to='Raster/%Y_%m_%d/')),
                ('DSM', models.ImageField(upload_to='DSM/%Y_%m_%d/')),
                ('DTM', models.ImageField(upload_to='DTM/%Y_%m_%d/')),
                ('Flow', models.ImageField(upload_to='Flow/%Y_%m_%d/')),
                ('Vari', models.ImageField(upload_to='Vari/%Y_%m_%d/')),
                ('IMG_bound_1', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
                ('IMG_bound_2', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
                ('Upload_Date', models.DateField(auto_now_add=True)),
                ('Plantation_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='location.plantation')),
            ],
        ),
    ]
