# Generated by Django 4.1.4 on 2023-01-14 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0015_alter_trees_listed_date_plantation_gis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantation_gis',
            name='DSM',
            field=models.ImageField(null=True, upload_to='DSM/%Y_%m_%d/'),
        ),
        migrations.AlterField(
            model_name='plantation_gis',
            name='DTM',
            field=models.ImageField(null=True, upload_to='DTM/%Y_%m_%d/'),
        ),
        migrations.AlterField(
            model_name='plantation_gis',
            name='Flow',
            field=models.ImageField(null=True, upload_to='Flow/%Y_%m_%d/'),
        ),
        migrations.AlterField(
            model_name='plantation_gis',
            name='Raster',
            field=models.ImageField(null=True, upload_to='Raster/%Y_%m_%d/'),
        ),
        migrations.AlterField(
            model_name='plantation_gis',
            name='Vari',
            field=models.ImageField(null=True, upload_to='Vari/%Y_%m_%d/'),
        ),
    ]
